// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimuladorCajero.Data.Context;

#nullable disable

namespace SimuladorCajero.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130055129_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cuenta", b =>
                {
                    b.Property<int>("CuentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuentaId"));

                    b.Property<double>("Saldo")
                        .HasColumnType("float");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CuentaId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Cuentas");

                    b.HasDiscriminator<string>("TipoCuenta").HasValue("Cuenta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SimuladorCajero.Models.TarjetaCredito", b =>
                {
                    b.Property<int>("TarjetaCreditoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarjetaCreditoId"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<double>("Cupo")
                        .HasColumnType("float");

                    b.Property<double>("Deuda")
                        .HasColumnType("float");

                    b.Property<string>("NumeroTarjeta")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TarjetaCreditoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("TarjetasCredito");
                });

            modelBuilder.Entity("SimuladorCajero.Models.Transaccion", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaccionId"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("TransaccionId");

                    b.HasIndex("CuentaId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SimuladorCajero.Models.Ahorros", b =>
                {
                    b.HasBaseType("Cuenta");

                    b.Property<double>("InteresMensual")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Ahorros");
                });

            modelBuilder.Entity("SimuladorCajero.Models.Corriente", b =>
                {
                    b.HasBaseType("Cuenta");

                    b.Property<double>("CupoSobregiro")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Corriente");
                });

            modelBuilder.Entity("Cuenta", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithOne("Cuenta")
                        .HasForeignKey("Cuenta", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SimuladorCajero.Models.TarjetaCredito", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithOne("TarjetaCredito")
                        .HasForeignKey("SimuladorCajero.Models.TarjetaCredito", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SimuladorCajero.Models.Transaccion", b =>
                {
                    b.HasOne("Cuenta", "Cuenta")
                        .WithMany("Transacciones")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("Cuenta", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("Cuenta");

                    b.Navigation("TarjetaCredito");
                });
#pragma warning restore 612, 618
        }
    }
}
